"""RunningHub Qwen3-TTS -> LTX 2.3 dialogue video orchestrator.

The MCP server accepts a two-person image and dialogue script, submits the
script to a Qwen3-TTS AI App, waits asynchronously through later query calls,
uploads the resulting audio back to RunningHub, and then submits an LTX 2.3
two-person dialogue video task.
"""

from __future__ import annotations

import asyncio
import copy
import ipaddress
import json
import logging
import mimetypes
import os
import re
import secrets
import socket
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urljoin, urlparse

import httpx
from dotenv import load_dotenv

os.environ.setdefault("FASTMCP_CHECK_FOR_UPDATES", "off")
os.environ.setdefault("FASTMCP_SHOW_CLI_BANNER", "false")

from fastmcp import FastMCP
from pydantic import BaseModel, ConfigDict, Field
from starlette.requests import Request
from starlette.responses import JSONResponse

from orchestrator_core import (
    ConfigurationError,
    LTX_ROLE_ALIASES,
    TTS_ROLE_ALIASES,
    NodeTarget,
    PipelineRecord,
    PipelineStore,
    ensure_text,
    env_bool,
    env_float,
    env_int,
    extract_failure_reason,
    extract_media_urls,
    infer_node_map,
    make_node_info_list,
    parse_extra_node_info,
    parse_node_map,
    summarize_nodes,
    validate_ltx_numbers,
)


load_dotenv()

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("runninghub-qwen-ltx-orchestrator")


# Known-good input mappings for the two RunningHub AI Apps used by this
# deployment. RunningHub exposes the Qwen text inputs only as generic
# ``String / inStr`` fields, so semantic auto-discovery cannot distinguish the
# dialogue script from the speaker voice prompts. These defaults are applied
# only while the configured WebApp IDs still match the known applications.
# A non-empty Railway environment variable always takes precedence.
DEFAULT_QWEN_TTS_WEBAPP_ID = "2051851200194195458"
DEFAULT_LTX23_WEBAPP_ID = "2048763193677324290"
DEFAULT_LTX23_WORKFLOW_ID = "2092528826571116545"

# The exported workflow contains two independent positive-prompt fields on
# node #281. Both must be replaced. If only ``global_prompt`` is changed, the
# original cafe dialogue in ``local_prompts`` still drives the generated
# characters, actions, and background.
LTX_NODE_ROLE_ALIASES = dict(LTX_ROLE_ALIASES)
LTX_NODE_ROLE_ALIASES["local_prompt"] = (
    "local_prompts",
    "local_prompt",
    "timeline_prompt",
    "shot_prompt",
    "局部提示词",
    "分镜提示词",
    "时间线提示词",
)

DEFAULT_QWEN_TTS_NODE_MAP_JSON = json.dumps(
    {
        "script": {"nodeId": "10", "fieldName": "inStr"},
        "voice_a": {"nodeId": "14", "fieldName": "inStr"},
        "voice_b": {"nodeId": "15", "fieldName": "inStr"},
    },
    separators=(",", ":"),
)

DEFAULT_LTX23_NODE_MAP_JSON = json.dumps(
    {
        "image": {"nodeId": "61", "fieldName": "image"},
        "audio": {"nodeId": "60", "fieldName": "audio"},
        "prompt": {"nodeId": "281", "fieldName": "global_prompt"},
        "local_prompt": {"nodeId": "281", "fieldName": "local_prompts"},
        "negative_prompt": {"nodeId": "4", "fieldName": "text"},
        "fps": {"nodeId": "62", "fieldName": "value"},
    },
    separators=(",", ":"),
)

# Always sent to node #4 in addition to the workflow's own negative prompt.
# Keeping these concepts out of the positive prompts and strengthening them
# here substantially reduces pseudo-Chinese captions generated by LTX itself.
MANDATORY_NO_TEXT_NEGATIVE = (
    "(subtitles:2.0), (captions:2.0), (Chinese characters:2.0), "
    "(text overlay:2.0), (letters:1.8), (typography:1.8), "
    "(lower thirds:2.0), speech bubbles, title cards, credits, "
    "interface text, logos, watermark"
)

_TIME_TAG_RE = re.compile(
    r"\[\s*\d+(?:\.\d+)?\s*(?:-|–|—|~|至)\s*"
    r"\d+(?:\.\d+)?\s*(?:s|sec|secs|seconds?|秒)\s*\]",
    re.IGNORECASE,
)

_QUOTED_DIALOGUE_RE = re.compile(
    r"“[^”\n]*”|「[^」\n]*」|『[^』\n]*』|\"[^\"\n]*\""
)

_SPEECH_QUOTED_AFTER_COLON_RE = re.compile(
    r"(?P<prefix>"
    r"(?:says?|asks?|replies?|answers?|speaks?|"
    r"轻声说|低声说|平静地说|缓缓说道|说道|说|问道|问|回答|答道)"
    r"[^:：\n|]{0,60})"
    r"\s*[:：]\s*"
    r"(?:“[^”\n]*”|「[^」\n]*」|『[^』\n]*』|\"[^\"\n]*\")",
    re.IGNORECASE,
)

_SPEECH_AFTER_COLON_RE = re.compile(
    r"(?P<prefix>"
    r"(?:says?|asks?|replies?|answers?|speaks?|"
    r"轻声说|低声说|平静地说|缓缓说道|说道|说|问道|问|回答|答道)"
    r"[^:：\n|]{0,60})"
    r"\s*[:：]\s*[^。！？!?\n|]*(?:[。！？!?]|$)",
    re.IGNORECASE,
)

_DIALOGUE_LINE_RE = re.compile(
    r"^\s*(?:角色|人物|speaker|character)?\s*[A-Za-z甲乙丙丁0-9一二三四]*"
    r"\s*[:：]\s*(?P<utterance>.+?)\s*$",
    re.IGNORECASE,
)

_POSITIVE_TEXT_CONCEPT_PATTERNS = (
    re.compile(
        r"\b(?:clear\s+)?(?:natural\s+)?mandarin(?:\s+chinese)?\s+dialogue\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b(?:no|without)\s+(?:subtitles?|captions?|"
        r"text(?:\s+on\s+(?:the\s+)?screen)?)\b",
        re.IGNORECASE,
    ),
    re.compile(r"\b(?:subtitles?|captions?|text\s+overlay|lower\s+thirds?)\b", re.IGNORECASE),
    re.compile(r"(?:无|不要|没有|不显示|不出现)(?:中文)?(?:字幕|文字)"),
    re.compile(r"(?:中文字幕|字幕|文字)"),
)


def node_map_json_from_env(
    variable_name: str,
    *,
    configured_webapp_id: str,
    default_webapp_id: str,
    default_json: str,
) -> str:
    """Return an explicit override, or the known mapping for the default app."""

    configured = os.getenv(variable_name, "").strip()
    if configured:
        return configured
    if configured_webapp_id == default_webapp_id:
        return default_json
    return ""


class RunningHubAPIError(RuntimeError):
    """Sanitized RunningHub error safe to return through MCP."""

    def __init__(self, message: str, *, code: str | int | None = None) -> None:
        super().__init__(message)
        self.code = code


class OpenAIFile(BaseModel):
    """ChatGPT attachment parameter supplied to a remote MCP tool."""

    model_config = ConfigDict(extra="forbid")

    download_url: str = Field(description="Temporary URL downloadable by the MCP server")
    file_id: str = Field(description="ChatGPT file identifier")
    mime_type: str = Field(default=None, description="File MIME type")  # type: ignore[assignment]
    file_name: str = Field(default=None, description="Original file name")  # type: ignore[assignment]


def finalize_openai_file_param_schema(tool: Any, *parameter_names: str) -> None:
    """Adjust FastMCP JSON Schema to ChatGPT's file-parameter contract."""

    properties = tool.parameters.get("properties", {})
    for parameter_name in parameter_names:
        file_schema = properties.get(parameter_name)
        if not isinstance(file_schema, dict):
            raise RuntimeError(f"Missing file parameter schema: {parameter_name}")
        file_schema["additionalProperties"] = False
        for optional_name in ("mime_type", "file_name"):
            optional_schema = file_schema.get("properties", {}).get(optional_name, {})
            optional_schema.pop("default", None)


@dataclass(frozen=True)
class AppConfig:
    name: str
    webapp_id: str
    access_password: str
    node_map: dict[str, NodeTarget] = field(default_factory=dict)
    extra_node_info: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True)
class Settings:
    api_key: str
    base_url: str
    upload_path: str
    qwen: AppConfig
    ltx: AppConfig
    ltx_mode: str
    ltx_workflow_id: str
    ltx_workflow_api_file: str
    auto_discover_nodes: bool
    http_timeout_seconds: float
    poll_interval_seconds: float
    max_remote_file_bytes: int
    state_file: str
    state_max_records: int
    state_ttl_seconds: int

    @classmethod
    def from_env(cls, *, require_credentials: bool = True) -> "Settings":
        api_key = os.getenv("RUNNINGHUB_API_KEY", "").strip()
        if require_credentials and not api_key:
            raise ConfigurationError("缺少 RUNNINGHUB_API_KEY。")

        base_url = os.getenv("RUNNINGHUB_BASE_URL", "https://www.runninghub.cn").strip().rstrip("/")
        parsed = urlparse(base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            raise ConfigurationError("RUNNINGHUB_BASE_URL 必须是有效的 HTTP(S) 地址。")

        upload_path = os.getenv(
            "RUNNINGHUB_UPLOAD_PATH", "/openapi/v2/media/upload/binary"
        ).strip()
        if not upload_path.startswith("/"):
            upload_path = f"/{upload_path}"

        qwen_id = os.getenv("QWEN_TTS_WEBAPP_ID", DEFAULT_QWEN_TTS_WEBAPP_ID).strip()
        ltx_id = os.getenv(
            "LTX23_WEBAPP_ID",
            os.getenv("RUNNINGHUB_WEBAPP_ID", DEFAULT_LTX23_WEBAPP_ID),
        ).strip()
        if require_credentials and not qwen_id:
            raise ConfigurationError("缺少 QWEN_TTS_WEBAPP_ID。")
        if require_credentials and not ltx_id and os.getenv("LTX23_MODE", "workflow").strip().lower() == "ai_app":
            raise ConfigurationError("缺少 LTX23_WEBAPP_ID。")

        ltx_mode = os.getenv("LTX23_MODE", "workflow").strip().lower()
        if ltx_mode not in {"workflow", "ai_app"}:
            raise ConfigurationError("LTX23_MODE 只允许 workflow 或 ai_app。")
        ltx_workflow_id = os.getenv(
            "LTX23_WORKFLOW_ID", DEFAULT_LTX23_WORKFLOW_ID
        ).strip()
        ltx_workflow_api_file = os.getenv(
            "LTX23_WORKFLOW_API_FILE",
            str(Path(__file__).resolve().with_name("ltx23_workflow_api.json")),
        ).strip()
        if ltx_mode == "workflow" and require_credentials:
            if not ltx_workflow_id:
                raise ConfigurationError(
                    "工作流模式缺少 LTX23_WORKFLOW_ID；请填写 RunningHub 工作流页面 URL 中的数字 ID。"
                )
            if not ltx_workflow_api_file:
                raise ConfigurationError("工作流模式缺少 LTX23_WORKFLOW_API_FILE。")
            if not Path(ltx_workflow_api_file).is_file():
                raise ConfigurationError(
                    "找不到 LTX API 工作流文件："
                    f"{ltx_workflow_api_file}。请把导出的 API JSON 放入部署仓库。"
                )

        qwen = AppConfig(
            name="qwen_tts",
            webapp_id=qwen_id,
            access_password=os.getenv("QWEN_TTS_ACCESS_PASSWORD", "").strip(),
            node_map=parse_node_map(
                node_map_json_from_env(
                    "QWEN_TTS_NODE_MAP_JSON",
                    configured_webapp_id=qwen_id,
                    default_webapp_id=DEFAULT_QWEN_TTS_WEBAPP_ID,
                    default_json=DEFAULT_QWEN_TTS_NODE_MAP_JSON,
                ),
                TTS_ROLE_ALIASES,
                "QWEN_TTS_NODE_MAP_JSON",
            ),
            extra_node_info=parse_extra_node_info(
                os.getenv("QWEN_TTS_EXTRA_NODE_INFO_JSON", ""),
                "QWEN_TTS_EXTRA_NODE_INFO_JSON",
            ),
        )
        ltx_node_map_raw = os.getenv("LTX23_NODE_MAP_JSON", "").strip()
        if not ltx_node_map_raw and ltx_mode == "workflow":
            ltx_node_map_raw = DEFAULT_LTX23_NODE_MAP_JSON
        elif not ltx_node_map_raw:
            ltx_node_map_raw = node_map_json_from_env(
                "LTX23_NODE_MAP_JSON",
                configured_webapp_id=ltx_id,
                default_webapp_id=DEFAULT_LTX23_WEBAPP_ID,
                default_json=DEFAULT_LTX23_NODE_MAP_JSON,
            )

        ltx = AppConfig(
            name="ltx23",
            webapp_id=ltx_id,
            access_password=os.getenv("LTX23_ACCESS_PASSWORD", "").strip(),
            node_map=parse_node_map(
                ltx_node_map_raw,
                LTX_NODE_ROLE_ALIASES,
                "LTX23_NODE_MAP_JSON",
            ),
            extra_node_info=parse_extra_node_info(
                os.getenv("LTX23_EXTRA_NODE_INFO_JSON", ""),
                "LTX23_EXTRA_NODE_INFO_JSON",
            ),
        )

        return cls(
            api_key=api_key,
            base_url=base_url,
            upload_path=upload_path,
            qwen=qwen,
            ltx=ltx,
            ltx_mode=ltx_mode,
            ltx_workflow_id=ltx_workflow_id,
            ltx_workflow_api_file=ltx_workflow_api_file,
            auto_discover_nodes=env_bool("RUNNINGHUB_AUTO_DISCOVER_NODES", True),
            http_timeout_seconds=env_float(
                "RUNNINGHUB_HTTP_TIMEOUT_SECONDS", 120.0, minimum=10.0, maximum=600.0
            ),
            poll_interval_seconds=env_float(
                "RUNNINGHUB_POLL_INTERVAL_SECONDS", 5.0, minimum=1.0, maximum=30.0
            ),
            max_remote_file_bytes=env_int(
                "MAX_REMOTE_FILE_BYTES",
                200 * 1024 * 1024,
                minimum=1 * 1024 * 1024,
                maximum=1024 * 1024 * 1024,
            ),
            state_file=os.getenv(
                "PIPELINE_STATE_FILE", "/tmp/runninghub-dialogue-pipelines.json"
            ).strip()
            or "/tmp/runninghub-dialogue-pipelines.json",
            state_max_records=env_int(
                "PIPELINE_STATE_MAX_RECORDS", 200, minimum=10, maximum=5000
            ),
            state_ttl_seconds=env_int(
                "PIPELINE_STATE_TTL_SECONDS", 604800, minimum=3600, maximum=2592000
            ),
        )


def load_ltx_workflow_api(settings: Settings) -> dict[str, Any]:
    """Load and validate the exported ComfyUI API-format workflow."""

    path = Path(settings.ltx_workflow_api_file)
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ConfigurationError(f"无法读取 LTX API 工作流文件：{path}。") from exc
    except json.JSONDecodeError as exc:
        raise ConfigurationError(
            f"LTX API 工作流文件不是有效 JSON：{exc.msg}。"
        ) from exc
    if not isinstance(payload, dict) or not payload:
        raise ConfigurationError("LTX API 工作流必须是以节点 ID 为键的 JSON 对象。")
    return payload


def apply_workflow_overrides(
    workflow: dict[str, Any], node_info_list: list[dict[str, Any]]
) -> dict[str, Any]:
    """Write overrides into a private copy of the actual API workflow."""

    runtime = copy.deepcopy(workflow)
    for item in node_info_list:
        node_id = str(item.get("nodeId") or "").strip()
        field_name = str(item.get("fieldName") or "").strip()
        if not node_id or not field_name or "fieldValue" not in item:
            raise ConfigurationError("工作流覆盖项缺少 nodeId、fieldName 或 fieldValue。")
        node = runtime.get(node_id)
        if not isinstance(node, dict):
            raise ConfigurationError(f"LTX API 工作流中不存在节点 #{node_id}。")
        inputs = node.get("inputs")
        if not isinstance(inputs, dict):
            raise ConfigurationError(f"LTX API 工作流节点 #{node_id} 缺少 inputs。")
        if field_name not in inputs:
            raise ConfigurationError(
                f"LTX API 工作流节点 #{node_id} 不包含字段 {field_name!r}。"
            )
        inputs[field_name] = item["fieldValue"]
    return runtime


def inspect_ltx_workflow(settings: Settings) -> dict[str, Any]:
    workflow = load_ltx_workflow_api(settings)
    resolved = dict(settings.ltx.node_map)
    required_roles = ("image", "audio", "prompt", "local_prompt")
    missing = [role for role in required_roles if role not in resolved]
    available_nodes: list[dict[str, Any]] = []
    invalid_mappings: list[str] = []

    for role, target in sorted(resolved.items()):
        node = workflow.get(target.node_id)
        inputs = node.get("inputs") if isinstance(node, dict) else None
        if not isinstance(inputs, dict) or target.field_name not in inputs:
            invalid_mappings.append(role)
            continue
        meta = node.get("_meta") if isinstance(node.get("_meta"), dict) else {}
        available_nodes.append(
            {
                "role": role,
                "nodeId": target.node_id,
                "nodeName": str(node.get("class_type") or ""),
                "fieldName": target.field_name,
                "description": str(meta.get("title") or ""),
                "defaultValue": inputs.get(target.field_name),
            }
        )

    missing.extend(role for role in invalid_mappings if role not in missing)
    return {
        "ok": not missing,
        "mode": "workflow",
        "workflow_id": settings.ltx_workflow_id,
        "workflow_api_file": settings.ltx_workflow_api_file,
        "resolved_node_map": {
            role: target.to_dict() for role, target in sorted(resolved.items())
        },
        "missing_required_roles": missing,
        "available_nodes": available_nodes,
    }


class RunningHubClient:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    @property
    def headers(self) -> dict[str, str]:
        return {
            "Accept": "application/json",
            "Authorization": f"Bearer {self.settings.api_key}",
            "User-Agent": "runninghub-qwen-ltx-orchestrator/2.0",
        }

    def _unwrap(self, body: Any) -> Any:
        if not isinstance(body, dict) or "code" not in body:
            return body
        code = body.get("code")
        if str(code) not in {"0", "200"}:
            message = str(body.get("msg") or body.get("message") or "未知错误")
            message = message.replace(self.settings.api_key, "***")
            raise RunningHubAPIError(f"RunningHub API 错误 {code}：{message}", code=code)
        return body.get("data")

    async def request_json(
        self,
        method: str,
        path: str,
        *,
        payload: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> Any:
        method = method.upper()
        request_payload = dict(payload or {})
        request_params = dict(params or {})
        if method == "GET":
            request_params["apiKey"] = self.settings.api_key
        else:
            request_payload["apiKey"] = self.settings.api_key

        headers = dict(self.headers)
        if method != "GET":
            headers["Content-Type"] = "application/json"
        transient = {408, 425, 429, 500, 502, 503, 504}

        for attempt in range(3):
            try:
                async with httpx.AsyncClient(
                    base_url=self.settings.base_url,
                    timeout=self.settings.http_timeout_seconds,
                    headers=headers,
                    follow_redirects=True,
                ) as http:
                    response = await http.request(
                        method,
                        path,
                        json=request_payload if method != "GET" else None,
                        params=request_params or None,
                    )
            except httpx.RequestError as exc:
                if attempt < 2:
                    await asyncio.sleep(1.5 * (2**attempt))
                    continue
                raise RunningHubAPIError(
                    f"无法连接 RunningHub：{type(exc).__name__}。"
                ) from exc

            if response.status_code in transient and attempt < 2:
                await asyncio.sleep(1.5 * (2**attempt))
                continue
            if response.is_error:
                safe_text = response.text.replace(self.settings.api_key, "***")[:500]
                raise RunningHubAPIError(
                    f"RunningHub HTTP {response.status_code}：{safe_text or '请求失败'}",
                    code=response.status_code,
                )
            try:
                return self._unwrap(response.json())
            except ValueError as exc:
                raise RunningHubAPIError("RunningHub 返回了非 JSON 响应。") from exc
        raise RunningHubAPIError("RunningHub 请求在重试后仍然失败。")

    async def get_ai_app_demo(self, webapp_id: str) -> dict[str, Any]:
        data = await self.request_json(
            "GET", "/api/webapp/apiCallDemo", params={"webappId": webapp_id}
        )
        if not isinstance(data, dict):
            raise RunningHubAPIError("AI 应用调用示例返回格式不正确。")
        return data

    async def run_ai_app(
        self, app: AppConfig, node_info_list: list[dict[str, Any]]
    ) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "webappId": app.webapp_id,
            "nodeInfoList": node_info_list,
        }
        if app.access_password:
            payload["accessPassword"] = app.access_password
        data = await self.request_json("POST", "/task/openapi/ai-app/run", payload=payload)
        if not isinstance(data, dict) or not data.get("taskId"):
            raise RunningHubAPIError("RunningHub 未返回 taskId，任务没有成功创建。")
        prompt_tips = data.get("promptTips")
        if isinstance(prompt_tips, str):
            try:
                prompt_tips = json.loads(prompt_tips)
            except json.JSONDecodeError:
                pass
        if isinstance(prompt_tips, dict) and prompt_tips.get("node_errors"):
            raise RunningHubAPIError(
                f"RunningHub 节点校验失败：{prompt_tips['node_errors']}"
            )
        return data

    async def run_workflow(
        self,
        *,
        workflow_id: str,
        node_info_list: list[dict[str, Any]],
        access_password: str = "",
    ) -> dict[str, Any]:
        """Run the exported workflow directly, bypassing the AI App layer."""

        payload: dict[str, Any] = {
            "workflowId": workflow_id,
            "nodeInfoList": node_info_list,
            "addMetadata": False,
        }
        if access_password:
            payload["accessPassword"] = access_password
        data = await self.request_json(
            "POST", "/task/openapi/create", payload=payload
        )
        if not isinstance(data, dict) or not data.get("taskId"):
            raise RunningHubAPIError(
                "RunningHub 工作流 API 未返回 taskId，任务没有成功创建。"
            )
        prompt_tips = data.get("promptTips")
        if isinstance(prompt_tips, str):
            try:
                prompt_tips = json.loads(prompt_tips)
            except json.JSONDecodeError:
                pass
        if isinstance(prompt_tips, dict) and prompt_tips.get("node_errors"):
            raise RunningHubAPIError(
                f"RunningHub 工作流节点校验失败：{prompt_tips['node_errors']}"
            )
        return data

    async def get_outputs(self, task_id: str) -> Any:
        return await self.request_json(
            "POST", "/task/openapi/outputs", payload={"taskId": task_id}
        )

    async def upload_bytes(self, content: bytes, filename: str, content_type: str) -> str:
        if not content:
            raise ValueError(f"{filename} 是空文件。")
        headers = dict(self.headers)
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(
                    base_url=self.settings.base_url,
                    timeout=max(self.settings.http_timeout_seconds, 300.0),
                    headers=headers,
                    follow_redirects=True,
                ) as http:
                    response = await http.post(
                        self.settings.upload_path,
                        files={"file": (filename, content, content_type)},
                    )
            except httpx.RequestError as exc:
                if attempt < 2:
                    await asyncio.sleep(1.5 * (2**attempt))
                    continue
                raise RunningHubAPIError(
                    f"上传到 RunningHub 失败：{type(exc).__name__}。"
                ) from exc
            if response.status_code in {408, 425, 429, 500, 502, 503, 504} and attempt < 2:
                await asyncio.sleep(1.5 * (2**attempt))
                continue
            if response.is_error:
                safe_text = response.text.replace(self.settings.api_key, "***")[:500]
                raise RunningHubAPIError(
                    f"RunningHub 上传 HTTP {response.status_code}：{safe_text}",
                    code=response.status_code,
                )
            try:
                data = self._unwrap(response.json())
            except ValueError as exc:
                raise RunningHubAPIError("RunningHub 上传接口返回了非 JSON 响应。") from exc
            if not isinstance(data, dict):
                raise RunningHubAPIError("RunningHub 上传接口没有返回文件信息。")
            # RunningHub's ComfyUI upload contract names the canonical loader
            # path ``fileName`` (for example ``openapi/<hash>.png``). Prefer it
            # over the more generic ``filename`` field in case both are ever
            # returned with different meanings.
            uploaded = str(
                data.get("fileName") or data.get("filename") or data.get("name") or ""
            ).strip()
            if not uploaded:
                raise RunningHubAPIError("RunningHub 上传成功响应中缺少 filename。")
            # A freshly uploaded ComfyUI resource must be a server-relative
            # loader path such as api/... or openapi/.... A bare basename can
            # silently fall back to the AI App's template asset, which wastes
            # credits while producing the default characters and background.
            if "/" not in uploaded:
                raise RunningHubAPIError(
                    "RunningHub 上传返回了不可用于加载节点的裸文件名："
                    f"{uploaded}。期望 fileName 类似 openapi/<hash>.<ext>；"
                    "已在创建生成任务前停止。"
                )
            logger.info(
                "RunningHub media upload selected fileName=%s source=%s content_type=%s",
                uploaded,
                Path(filename).name,
                content_type,
            )
            return uploaded
        raise RunningHubAPIError("RunningHub 上传在重试后仍然失败。")


_discovery_cache: dict[str, tuple[float, dict[str, Any]]] = {}
_pipeline_locks: dict[str, asyncio.Lock] = {}
_submit_lock = asyncio.Lock()


def get_store(settings: Settings) -> PipelineStore:
    return PipelineStore(
        settings.state_file,
        max_records=settings.state_max_records,
        ttl_seconds=settings.state_ttl_seconds,
    )


async def get_discovery(
    settings: Settings, client: RunningHubClient, app: AppConfig
) -> dict[str, Any]:
    cache_key = f"{settings.base_url}|{app.webapp_id}"
    cached = _discovery_cache.get(cache_key)
    if cached and time.monotonic() - cached[0] < 300:
        return cached[1]
    demo = await client.get_ai_app_demo(app.webapp_id)
    _discovery_cache[cache_key] = (time.monotonic(), demo)
    return demo


async def resolve_app_nodes(
    settings: Settings,
    client: RunningHubClient,
    app: AppConfig,
    aliases: dict[str, tuple[str, ...]],
) -> tuple[dict[str, NodeTarget], dict[str, Any]]:
    demo = await get_discovery(settings, client, app)
    nodes = [item for item in demo.get("nodeInfoList") or [] if isinstance(item, dict)]
    resolved: dict[str, NodeTarget] = {}
    if settings.auto_discover_nodes:
        resolved.update(infer_node_map(nodes, aliases))
    resolved.update(app.node_map)
    return resolved, demo


def _ensure_public_http_url(url: str) -> str:
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        raise ValueError("只支持 http:// 或 https:// 文件 URL。")
    if not parsed.hostname:
        raise ValueError("文件 URL 缺少主机名。")
    host = parsed.hostname.lower()
    if host in {"localhost", "localhost.localdomain"}:
        raise ValueError("不允许 localhost URL。")
    try:
        infos = socket.getaddrinfo(
            host, parsed.port or (443 if parsed.scheme == "https" else 80)
        )
    except socket.gaierror as exc:
        raise ValueError(f"无法解析文件 URL 主机：{host}") from exc
    for info in infos:
        ip = ipaddress.ip_address(info[4][0])
        if (
            ip.is_private
            or ip.is_loopback
            or ip.is_link_local
            or ip.is_multicast
            or ip.is_reserved
            or ip.is_unspecified
        ):
            raise ValueError("不允许访问私有或本地网络 URL。")
    return url


def _fallback_filename(url: str, preferred: str, kind: str) -> str:
    if preferred:
        return Path(preferred).name[:240]
    candidate = Path(unquote(urlparse(url).path)).name
    if candidate:
        return candidate[:240]
    return "input.png" if kind == "image" else "dialogue.wav"


def validate_media_type(filename: str, content_type: str, expected_kind: str) -> None:
    suffix = Path(filename).suffix.lower()
    mime = (content_type or "").split(";", 1)[0].strip().lower()
    image_extensions = {".jpg", ".jpeg", ".png", ".webp"}
    audio_extensions = {".wav", ".mp3", ".m4a", ".aac", ".flac", ".ogg", ".opus"}
    if expected_kind == "image":
        if not (mime.startswith("image/") or suffix in image_extensions):
            raise ValueError("双人首帧附件必须是 JPG、PNG 或 WebP 图片。")
    elif expected_kind == "audio":
        if not (mime.startswith("audio/") or suffix in audio_extensions):
            raise ValueError("对白附件必须是 WAV、MP3、M4A、AAC、FLAC、OGG 或 OPUS 音频。")
    else:
        raise ValueError("未知媒体类型。")


async def download_public_file(
    settings: Settings,
    url: str,
    *,
    preferred_filename: str = "",
    expected_kind: str,
) -> tuple[bytes, str, str]:
    current_url = _ensure_public_http_url(ensure_text("url", url, max_length=5000))
    async with httpx.AsyncClient(
        timeout=max(settings.http_timeout_seconds, 300.0), follow_redirects=False
    ) as http:
        for redirect_count in range(6):
            try:
                async with http.stream("GET", current_url) as response:
                    if response.status_code in {301, 302, 303, 307, 308}:
                        location = response.headers.get("location", "").strip()
                        if not location:
                            raise RunningHubAPIError("远程素材重定向缺少 Location。")
                        if redirect_count >= 5:
                            raise RunningHubAPIError("远程素材重定向次数过多。")
                        current_url = _ensure_public_http_url(urljoin(current_url, location))
                        continue
                    response.raise_for_status()
                    content_type = response.headers.get("content-type", "").split(";", 1)[0]
                    filename = _fallback_filename(
                        current_url, preferred_filename, expected_kind
                    )
                    chunks: list[bytes] = []
                    size = 0
                    async for chunk in response.aiter_bytes():
                        size += len(chunk)
                        if size > settings.max_remote_file_bytes:
                            raise ValueError(
                                f"远程文件超过 {settings.max_remote_file_bytes // (1024 * 1024)} MiB 限制。"
                            )
                        chunks.append(chunk)
                    break
            except httpx.HTTPError as exc:
                raise RunningHubAPIError(
                    f"下载远程素材失败：{type(exc).__name__}。"
                ) from exc
        else:  # pragma: no cover - loop always breaks or raises
            raise RunningHubAPIError("远程素材下载失败。")
    validate_media_type(filename, content_type, expected_kind)
    guessed = content_type or mimetypes.guess_type(filename)[0] or "application/octet-stream"
    return b"".join(chunks), filename, guessed


async def upload_file_object(
    client: RunningHubClient,
    settings: Settings,
    file: OpenAIFile,
    *,
    expected_kind: str,
) -> str:
    content, filename, content_type = await download_public_file(
        settings,
        file.download_url,
        preferred_filename=file.file_name or "",
        expected_kind=expected_kind,
    )
    if file.mime_type:
        validate_media_type(filename, file.mime_type, expected_kind)
        content_type = file.mime_type
    return await client.upload_bytes(content, filename, content_type)


async def upload_url(
    client: RunningHubClient,
    settings: Settings,
    url: str,
    *,
    expected_kind: str,
) -> str:
    content, filename, content_type = await download_public_file(
        settings, url, expected_kind=expected_kind
    )
    return await client.upload_bytes(content, filename, content_type)


def tts_values(
    *,
    dialogue_script: str,
    voice_a_prompt: str,
    voice_b_prompt: str,
    sentence_pause: float,
    punctuation_pause: float,
    seed: int,
) -> dict[str, Any]:
    dialogue_script = ensure_text("dialogue_script", dialogue_script, max_length=12000)
    if not dialogue_script:
        raise ValueError("dialogue_script 不能为空。")
    if sentence_pause < 0 or sentence_pause > 10:
        raise ValueError("sentence_pause 必须在 0–10 之间；0 表示使用应用默认值。")
    if punctuation_pause < 0 or punctuation_pause > 10:
        raise ValueError("punctuation_pause 必须在 0–10 之间；0 表示使用应用默认值。")
    if seed < -1:
        raise ValueError("tts_seed 必须为 -1 或非负整数。")
    return {
        "script": dialogue_script,
        "voice_a": ensure_text("voice_a_prompt", voice_a_prompt, max_length=2000),
        "voice_b": ensure_text("voice_b_prompt", voice_b_prompt, max_length=2000),
        "sentence_pause": sentence_pause if sentence_pause > 0 else None,
        "punctuation_pause": punctuation_pause if punctuation_pause > 0 else None,
        "seed": seed if seed >= 0 else None,
    }


def extract_dialogue_utterances(dialogue_script: str) -> list[str]:
    """Extract spoken lines so none can leak into LTX visual conditioning."""

    result: list[str] = []
    for line in str(dialogue_script or "").splitlines():
        match = _DIALOGUE_LINE_RE.match(line)
        if not match:
            continue
        utterance = match.group("utterance").strip(" \t\"'“”「」『』")
        if len(utterance) >= 2 and utterance not in result:
            result.append(utterance)
        without_terminal = utterance.rstrip("。！？!?….,， ")
        if len(without_terminal) >= 4 and without_terminal not in result:
            result.append(without_terminal)
    result.sort(key=len, reverse=True)
    return result


def sanitize_visual_prompt(value: str, dialogue_script: str = "") -> str:
    """Remove literal speech and text-rendering instructions from LTX visuals.

    The dialogue itself is already carried by the uploaded Qwen audio. Sending
    the same words into LTX's visual text encoder encourages the video model to
    draw those words as unstable pseudo-subtitles, so visual prompts retain
    only who speaks, who listens, timing, action, identity, scene, and camera.
    """

    text = str(value or "").strip()
    if not text:
        return ""
    # Strip the quoted utterance together with its speech delimiter first.
    # This preserves any following visual action, e.g. “A answers: ‘...’; B nods”.
    text = _SPEECH_QUOTED_AFTER_COLON_RE.sub(
        lambda match: f"{match.group('prefix').rstrip()}; ", text
    )
    text = _SPEECH_AFTER_COLON_RE.sub(
        lambda match: f"{match.group('prefix').rstrip()}; ", text
    )
    text = _QUOTED_DIALOGUE_RE.sub("", text)
    for utterance in extract_dialogue_utterances(dialogue_script):
        text = text.replace(utterance, "")
    text = _POSITIVE_TEXT_CONCEPT_PATTERNS[0].sub(
        "natural speech performance", text
    )
    for pattern in _POSITIVE_TEXT_CONCEPT_PATTERNS[1:]:
        text = pattern.sub("", text)
    text = re.sub(
        r"(?:普通话|中文|汉语)(?:自然)?对白",
        "自然说话动作",
        text,
    )
    text = re.sub(r"\b(?:and|or)\s*(?=[,.;]|$)", "", text, flags=re.IGNORECASE)
    text = re.sub(r"[ \t]+([,.;，。；])", r"\1", text)
    text = re.sub(r"[;；](?:\s*[;；])+", "; ", text)
    text = re.sub(r"([,.;，。；])(?:\s*\1)+", r"\1", text)
    cleaned_lines = [
        re.sub(r"[ \t]{2,}", " ", line).strip(" ,;，；")
        for line in text.splitlines()
    ]
    return "\n".join(line for line in cleaned_lines if line).strip()


def build_global_visual_prompt(inputs: dict[str, Any]) -> str:
    """Build node #281 global_prompt without dialogue literals or captions."""

    parts: list[str] = []
    dialogue_script = str(inputs.get("dialogue_script") or "")
    scene = sanitize_visual_prompt(
        str(inputs.get("video_prompt") or ""), dialogue_script
    )
    if scene:
        parts.append(scene)

    left = sanitize_visual_prompt(
        str(inputs.get("left_character") or ""), dialogue_script
    )
    right = sanitize_visual_prompt(
        str(inputs.get("right_character") or ""), dialogue_script
    )
    action = sanitize_visual_prompt(str(inputs.get("action") or ""), dialogue_script)
    camera = sanitize_visual_prompt(str(inputs.get("camera") or ""), dialogue_script)
    if left:
        parts.append(f"First-frame left character identity and costume: {left}")
    if right:
        parts.append(f"First-frame right character identity and costume: {right}")
    if action:
        parts.append(f"Visual performance and motion: {action}")
    if camera:
        parts.append(f"Camera and composition: {camera}")
    parts.append(
        "Use the uploaded first frame as the strict visual source. Preserve "
        "both character identities, faces, hairstyles, costumes, body "
        "proportions, left-right positions, environment, lighting, and "
        "composition throughout. The active speaker uses subtle natural lip "
        "motion synchronized to the supplied audio while the other character "
        "listens naturally."
    )
    return "\n".join(parts)


def build_local_visual_prompts(inputs: dict[str, Any]) -> str:
    """Build action-only PromptRelayEncode segments for node #281."""

    duration = int(inputs.get("duration_seconds") or 0) or 10
    timeline = sanitize_visual_prompt(
        str(inputs.get("speaker_timeline") or ""),
        str(inputs.get("dialogue_script") or ""),
    )
    segments: list[str] = []
    if timeline:
        matches = list(_TIME_TAG_RE.finditer(timeline))
        if matches:
            for index, match in enumerate(matches):
                end = matches[index + 1].start() if index + 1 < len(matches) else len(timeline)
                segment = timeline[match.start() : end].strip(" \t\r\n|")
                if segment:
                    segments.append(segment)
        else:
            segments.append(f"[0-{duration}s] {timeline}")
    if not segments:
        segments.append(
            f"[0-{duration}s] The active speaker uses subtle natural lip "
            "motion synchronized to the supplied audio while the other "
            "character remains in place and listens naturally."
        )

    identity_constraint = (
        "Preserve the exact first-frame faces, hairstyles, costumes, body "
        "proportions, left-right positions, environment, lighting, and "
        "composition."
    )
    return "\n\n|\n\n".join(
        f"{segment.rstrip()} {identity_constraint}" for segment in segments
    )


def build_negative_visual_prompt(inputs: dict[str, Any]) -> str:
    requested = str(inputs.get("negative_prompt") or "").strip(" ,")
    if not requested:
        return MANDATORY_NO_TEXT_NEGATIVE
    if MANDATORY_NO_TEXT_NEGATIVE.lower() in requested.lower():
        return requested
    return f"{requested}, {MANDATORY_NO_TEXT_NEGATIVE}"


def validate_prompt_separation(
    inputs: dict[str, Any], global_prompt: str, local_prompts: str
) -> None:
    """Stop before the paid LTX task if any known spoken line leaked visually."""

    combined = f"{global_prompt}\n{local_prompts}"
    leaked = [
        utterance
        for utterance in extract_dialogue_utterances(
            str(inputs.get("dialogue_script") or "")
        )
        if utterance and utterance in combined
    ]
    if leaked:
        raise ConfigurationError(
            "视觉提示词预检失败：检测到对白原文泄漏到 #281："
            + " | ".join(leaked[:3])
        )
    forbidden = (
        "subtitles",
        "caption",
        "text overlay",
        "lower thirds",
        "中文字幕",
        "字幕",
    )
    found = [term for term in forbidden if term.lower() in combined.lower()]
    if found:
        raise ConfigurationError(
            "视觉提示词预检失败：正向提示词仍包含文字渲染概念："
            + ", ".join(found)
        )


def ltx_values(image_filename: str, audio_filename: str, inputs: dict[str, Any]) -> dict[str, Any]:
    validate_ltx_numbers(
        width=int(inputs.get("width") or 0),
        height=int(inputs.get("height") or 0),
        duration_seconds=int(inputs.get("duration_seconds") or 0),
        frame_count=int(inputs.get("frame_count") or 0),
        fps=int(inputs.get("fps") or 0),
        seed=int(inputs.get("ltx_seed", -1)),
    )
    global_prompt = build_global_visual_prompt(inputs)
    local_prompts = build_local_visual_prompts(inputs)
    validate_prompt_separation(inputs, global_prompt, local_prompts)
    return {
        "image": image_filename,
        "audio": audio_filename,
        "prompt": global_prompt,
        "local_prompt": local_prompts,
        "negative_prompt": build_negative_visual_prompt(inputs),
        "width": int(inputs.get("width") or 0) or None,
        "height": int(inputs.get("height") or 0) or None,
        "aspect_ratio": str(inputs.get("aspect_ratio") or ""),
        "duration_seconds": int(inputs.get("duration_seconds") or 0) or None,
        "frame_count": int(inputs.get("frame_count") or 0) or None,
        "fps": int(inputs.get("fps") or 0) or None,
        "seed": int(inputs.get("ltx_seed", -1)) if int(inputs.get("ltx_seed", -1)) >= 0 else None,
    }


def pipeline_inputs(
    *,
    dialogue_script: str,
    voice_a_prompt: str,
    voice_b_prompt: str,
    sentence_pause: float,
    punctuation_pause: float,
    tts_seed: int,
    video_prompt: str,
    left_character: str,
    right_character: str,
    speaker_timeline: str,
    action: str,
    camera: str,
    negative_prompt: str,
    width: int,
    height: int,
    aspect_ratio: str,
    duration_seconds: int,
    frame_count: int,
    fps: int,
    ltx_seed: int,
    auto_start_ltx: bool,
) -> dict[str, Any]:
    # Validation occurs before a paid task is submitted.
    tts_values(
        dialogue_script=dialogue_script,
        voice_a_prompt=voice_a_prompt,
        voice_b_prompt=voice_b_prompt,
        sentence_pause=sentence_pause,
        punctuation_pause=punctuation_pause,
        seed=tts_seed,
    )
    validate_ltx_numbers(
        width=width,
        height=height,
        duration_seconds=duration_seconds,
        frame_count=frame_count,
        fps=fps,
        seed=ltx_seed,
    )
    if not ensure_text("video_prompt", video_prompt, max_length=6000):
        raise ValueError("video_prompt 不能为空。")
    return {
        "dialogue_script": dialogue_script.strip(),
        "voice_a_prompt": voice_a_prompt.strip(),
        "voice_b_prompt": voice_b_prompt.strip(),
        "sentence_pause": sentence_pause,
        "punctuation_pause": punctuation_pause,
        "tts_seed": tts_seed,
        "video_prompt": video_prompt.strip(),
        "left_character": ensure_text("left_character", left_character, max_length=1200),
        "right_character": ensure_text("right_character", right_character, max_length=1200),
        "speaker_timeline": ensure_text("speaker_timeline", speaker_timeline, max_length=3000),
        "action": ensure_text("action", action, max_length=3000),
        "camera": ensure_text("camera", camera, max_length=800),
        "negative_prompt": ensure_text("negative_prompt", negative_prompt, max_length=3000),
        "width": width,
        "height": height,
        "aspect_ratio": ensure_text("aspect_ratio", aspect_ratio, max_length=30),
        "duration_seconds": duration_seconds,
        "frame_count": frame_count,
        "fps": fps,
        "ltx_seed": ltx_seed,
        "auto_start_ltx": bool(auto_start_ltx),
    }


def pipeline_summary(record: PipelineRecord) -> dict[str, Any]:
    next_action = ""
    if record.status in {"TTS_SUBMITTED", "TTS_RUNNING", "LTX_SUBMITTED", "LTX_RUNNING"}:
        next_action = "稍后再次调用 query_dialogue_pipeline，并传入同一个 pipeline_id。"
    elif record.status == "WAITING_FOR_LTX":
        next_action = (
            "音频已经生成。检查 audio_url 后调用 continue_dialogue_pipeline_to_ltx；"
            "可以同时补充准确的 speaker_timeline。"
        )
    result = {
        "ok": record.status != "FAILED",
        "pipeline_id": record.pipeline_id,
        "status": record.status,
        "tts_task_id": record.tts_task_id,
        "ltx_task_id": record.ltx_task_id,
        "audio_url": record.audio_url,
        "video_urls": record.video_urls,
        "error": record.error,
        "created_at": record.created_at,
        "updated_at": record.updated_at,
        "next_action": next_action,
    }
    # These fields contain no credentials. They make it possible to verify
    # that an uploaded image really replaced the AI App template asset before
    # spending credits on another blind retry.
    uploaded_image = str(record.inputs.get("_uploaded_image_filename") or "")
    if uploaded_image:
        result["uploaded_image_filename"] = uploaded_image
    ltx_submission = record.inputs.get("_ltx_submitted_node_info")
    if isinstance(ltx_submission, list):
        result["ltx_submitted_node_info"] = ltx_submission
    image_preflight = record.inputs.get("_ltx_image_preflight")
    if isinstance(image_preflight, dict):
        result["ltx_image_preflight"] = image_preflight
    submission_mode = str(record.inputs.get("_ltx_submission_mode") or "")
    if submission_mode:
        result["ltx_submission_mode"] = submission_mode
    workflow_preflight = record.inputs.get("_ltx_workflow_preflight")
    if isinstance(workflow_preflight, dict):
        result["ltx_workflow_preflight"] = workflow_preflight
    return result


async def submit_tts_pipeline(
    *, image_filename: str, inputs: dict[str, Any]
) -> dict[str, Any]:
    settings = Settings.from_env()
    client = RunningHubClient(settings)
    qwen_map, _ = await resolve_app_nodes(
        settings, client, settings.qwen, TTS_ROLE_ALIASES
    )
    if "script" not in qwen_map:
        raise ConfigurationError(
            "无法确定 Qwen3-TTS 的剧本节点。请先调用 inspect_dialogue_pipeline，"
            "再配置 QWEN_TTS_NODE_MAP_JSON。"
        )

    values = tts_values(
        dialogue_script=str(inputs["dialogue_script"]),
        voice_a_prompt=str(inputs.get("voice_a_prompt") or ""),
        voice_b_prompt=str(inputs.get("voice_b_prompt") or ""),
        sentence_pause=float(inputs.get("sentence_pause") or 0),
        punctuation_pause=float(inputs.get("punctuation_pause") or 0),
        seed=int(inputs.get("tts_seed", -1)),
    )
    nodes = make_node_info_list(qwen_map, values, settings.qwen.extra_node_info)
    used_optional = {
        role for role in ("voice_a", "voice_b", "sentence_pause", "punctuation_pause", "seed")
        if values.get(role) is not None and values.get(role) != ""
    }
    unmapped_optional = sorted(role for role in used_optional if role not in qwen_map)

    async with _submit_lock:
        task = await client.run_ai_app(settings.qwen, nodes)

    now = time.time()
    record = PipelineRecord(
        pipeline_id=secrets.token_urlsafe(18),
        status="TTS_SUBMITTED",
        created_at=now,
        updated_at=now,
        image_filename=image_filename,
        tts_task_id=str(task["taskId"]),
        inputs=inputs,
    )
    await get_store(settings).put(record)
    result = pipeline_summary(record)
    result["warnings"] = (
        [
            "以下可选 Qwen 输入没有映射，将使用应用默认值："
            + ", ".join(unmapped_optional)
        ]
        if unmapped_optional
        else []
    )
    result["generation_will_consume_credits"] = True
    return result


async def submit_ltx_for_record(
    settings: Settings,
    client: RunningHubClient,
    record: PipelineRecord,
) -> PipelineRecord:
    workflow_template: dict[str, Any] | None = None
    if settings.ltx_mode == "workflow":
        # Workflow mode uses the explicit map against the exported API JSON;
        # it never asks the published AI App to infer or override image nodes.
        ltx_map = dict(settings.ltx.node_map)
        workflow_template = load_ltx_workflow_api(settings)
        demo: dict[str, Any] = {"nodeInfoList": []}
    else:
        ltx_map, demo = await resolve_app_nodes(
            settings, client, settings.ltx, LTX_NODE_ROLE_ALIASES
        )
    required_roles = (
        ("image", "audio", "prompt", "local_prompt")
        if settings.ltx_mode == "workflow"
        else ("image", "audio", "prompt")
    )
    missing = [role for role in required_roles if role not in ltx_map]
    if missing:
        raise ConfigurationError(
            "无法确定 LTX 2.3 必需节点："
            + ", ".join(missing)
            + "。请调用 inspect_dialogue_pipeline 并配置 LTX23_NODE_MAP_JSON。"
        )
    values = ltx_values(record.image_filename, record.audio_filename, record.inputs)
    if workflow_template is not None and "negative_prompt" in ltx_map:
        negative_target = ltx_map["negative_prompt"]
        negative_node = workflow_template.get(negative_target.node_id)
        negative_inputs = (
            negative_node.get("inputs")
            if isinstance(negative_node, dict)
            else None
        )
        template_negative = (
            str(negative_inputs.get(negative_target.field_name) or "").strip()
            if isinstance(negative_inputs, dict)
            else ""
        )
        requested_negative = str(values.get("negative_prompt") or "").strip()
        if template_negative and requested_negative:
            values["negative_prompt"] = f"{template_negative}, {requested_negative}"
        elif template_negative:
            values["negative_prompt"] = template_negative
    nodes = make_node_info_list(ltx_map, values, settings.ltx.extra_node_info)
    image_target = ltx_map["image"]
    submitted_image_nodes = [
        node
        for node in nodes
        if str(node.get("nodeId")) == image_target.node_id
        and str(node.get("fieldName")) == image_target.field_name
    ]
    if len(submitted_image_nodes) != 1:
        raise ConfigurationError(
            "LTX 图片预检失败：最终 nodeInfoList 中必须且只能包含一个图片覆盖项。"
        )
    submitted_image = str(submitted_image_nodes[0].get("fieldValue") or "").strip()
    if submitted_image != record.image_filename:
        raise ConfigurationError(
            "LTX 图片预检失败：提交值与 RunningHub 上传返回的 fileName 不一致。"
        )

    template_image = ""
    if workflow_template is not None:
        template_node = workflow_template.get(image_target.node_id)
        template_inputs = (
            template_node.get("inputs") if isinstance(template_node, dict) else None
        )
        if isinstance(template_inputs, dict):
            template_image = str(template_inputs.get(image_target.field_name) or "")
    else:
        demo_nodes = [
            item
            for item in demo.get("nodeInfoList") or []
            if isinstance(item, dict)
        ]
        for item in demo_nodes:
            if (
                str(item.get("nodeId")) == image_target.node_id
                and str(item.get("fieldName")) == image_target.field_name
            ):
                template_image = str(
                    item.get("defaultValue") or item.get("fieldValue") or ""
                )
                break
    if (
        settings.ltx_mode == "ai_app"
        and template_image
        and submitted_image == template_image
    ):
        raise ConfigurationError(
            "LTX 图片预检失败：上传图片仍等于 AI App 模板默认图片，"
            "已在创建任务前停止。"
        )

    validated_workflow: dict[str, Any] | None = None
    workflow_preflight: dict[str, Any] | None = None
    if workflow_template is not None:
        validated_workflow = apply_workflow_overrides(workflow_template, nodes)
        runtime_node = validated_workflow.get(image_target.node_id)
        runtime_inputs = (
            runtime_node.get("inputs") if isinstance(runtime_node, dict) else None
        )
        runtime_image = (
            str(runtime_inputs.get(image_target.field_name) or "")
            if isinstance(runtime_inputs, dict)
            else ""
        )
        if runtime_image != submitted_image:
            raise ConfigurationError(
                "LTX 工作流预检失败：完整 workflow 中的 #61 图片值没有被正确改写。"
            )
        workflow_preflight = {
            "ok": True,
            "workflowId": settings.ltx_workflow_id,
            "nodeId": image_target.node_id,
            "fieldName": image_target.field_name,
            "runtimeValue": runtime_image,
            "workflowOverridesTemplate": runtime_image != template_image,
            "positivePromptNode": ltx_map["prompt"].to_dict(),
            "localPromptNode": ltx_map["local_prompt"].to_dict(),
            "dialogueTextSeparatedFromVisualPrompts": True,
            "localPromptSegmentCount": str(values["local_prompt"]).count("|") + 1,
            "mandatoryNoTextNegativeApplied": (
                MANDATORY_NO_TEXT_NEGATIVE.lower()
                in str(values.get("negative_prompt") or "").lower()
            ),
        }

    record.inputs["_uploaded_image_filename"] = record.image_filename
    record.inputs["_ltx_submitted_node_info"] = [dict(node) for node in nodes]
    record.inputs["_ltx_submission_mode"] = settings.ltx_mode
    record.inputs["_ltx_image_preflight"] = {
        "ok": True,
        "nodeId": image_target.node_id,
        "fieldName": image_target.field_name,
        "submittedValue": submitted_image,
        "templateDefaultValue": template_image,
        "differsFromTemplateDefault": submitted_image != template_image,
    }
    if workflow_preflight is not None:
        record.inputs["_ltx_workflow_preflight"] = workflow_preflight
    await get_store(settings).put(record)
    logger.info(
        "LTX image preflight passed node=%s.%s submitted=%s template_default=%s",
        image_target.node_id,
        image_target.field_name,
        submitted_image,
        template_image,
    )
    async with _submit_lock:
        if validated_workflow is not None:
            task = await client.run_workflow(
                workflow_id=settings.ltx_workflow_id,
                node_info_list=nodes,
                access_password=settings.ltx.access_password,
            )
        else:
            task = await client.run_ai_app(settings.ltx, nodes)
    record.ltx_task_id = str(task["taskId"])
    record.status = "LTX_SUBMITTED"
    return await get_store(settings).put(record)


async def runninghub_task_state(
    client: RunningHubClient, task_id: str, media_kind: str
) -> tuple[str, list[str], str]:
    try:
        outputs = await client.get_outputs(task_id)
    except RunningHubAPIError as exc:
        code = str(exc.code)
        if code == "804":
            return "RUNNING", [], ""
        if code == "805":
            return "FAILED", [], "RunningHub 任务被中断、取消或内部状态异常。"
        raise
    urls = extract_media_urls(outputs, media_kind)
    if urls:
        return "SUCCESS", urls, ""
    reason = extract_failure_reason(outputs)
    if reason:
        return "FAILED", [], reason
    return "RUNNING", [], ""


async def advance_pipeline(record: PipelineRecord) -> PipelineRecord:
    settings = Settings.from_env()
    client = RunningHubClient(settings)
    store = get_store(settings)

    if record.status in {"SUCCESS", "FAILED"}:
        return record

    if record.status in {"TTS_SUBMITTED", "TTS_RUNNING"}:
        state, urls, reason = await runninghub_task_state(client, record.tts_task_id, "audio")
        if state == "FAILED":
            record.status = "FAILED"
            record.error = f"Qwen3-TTS 阶段失败：{reason}"
            return await store.put(record)
        if state == "RUNNING":
            record.status = "TTS_RUNNING"
            return await store.put(record)

        record.audio_url = urls[0]
        try:
            content, filename, content_type = await download_public_file(
                settings, record.audio_url, expected_kind="audio"
            )
            record.audio_filename = await client.upload_bytes(content, filename, content_type)
            record.status = "TTS_READY"
            record = await store.put(record)
            if not bool(record.inputs.get("auto_start_ltx", True)):
                record.status = "WAITING_FOR_LTX"
                return await store.put(record)
            return await submit_ltx_for_record(settings, client, record)
        except Exception as exc:
            record.status = "FAILED"
            record.error = f"音频转交给 LTX 失败：{str(exc)[:800]}"
            return await store.put(record)

    if record.status == "TTS_READY":
        try:
            return await submit_ltx_for_record(settings, client, record)
        except Exception as exc:
            record.status = "FAILED"
            record.error = f"LTX 提交失败：{str(exc)[:800]}"
            return await store.put(record)

    if record.status == "WAITING_FOR_LTX":
        return record

    if record.status in {"LTX_SUBMITTED", "LTX_RUNNING"}:
        state, urls, reason = await runninghub_task_state(client, record.ltx_task_id, "video")
        if state == "FAILED":
            record.status = "FAILED"
            record.error = f"LTX 2.3 阶段失败：{reason}"
        elif state == "SUCCESS":
            record.status = "SUCCESS"
            record.video_urls = urls
        else:
            record.status = "LTX_RUNNING"
        return await store.put(record)

    unknown_status = record.status
    record.status = "FAILED"
    record.error = f"未知流水线状态：{unknown_status}"
    return await store.put(record)


async def inspect_one_app(
    settings: Settings,
    client: RunningHubClient,
    app: AppConfig,
    aliases: dict[str, tuple[str, ...]],
    required_roles: tuple[str, ...],
) -> dict[str, Any]:
    resolved, demo = await resolve_app_nodes(settings, client, app, aliases)
    nodes = [item for item in demo.get("nodeInfoList") or [] if isinstance(item, dict)]
    missing = [role for role in required_roles if role not in resolved]
    return {
        "ok": not missing,
        "webapp_id": app.webapp_id,
        "webapp_name": str(demo.get("webappName", "")),
        "access_encrypted": bool(demo.get("accessEncrypted", False)),
        "resolved_node_map": {
            role: target.to_dict() for role, target in sorted(resolved.items())
        },
        "missing_required_roles": missing,
        "available_nodes": summarize_nodes(nodes),
    }


SERVER_INSTRUCTIONS = (
    "This server orchestrates a RunningHub Qwen3-TTS dialogue task followed by an "
    "LTX 2.3 two-person dialogue video task. Call inspect_dialogue_pipeline once "
    "after deployment. For a ChatGPT image attachment, call "
    "start_dialogue_video_from_script. It returns a pipeline_id. Repeatedly call "
    "query_dialogue_pipeline with that pipeline_id until SUCCESS or FAILED. "
    "Both stages consume RunningHub credits."
)

mcp = FastMCP("RunningHub Qwen3-TTS + LTX 2.3", instructions=SERVER_INSTRUCTIONS)


@mcp.tool(
    annotations={
        "readOnlyHint": True,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": True,
    }
)
async def inspect_dialogue_pipeline() -> dict[str, Any]:
    """只读检查 Qwen3-TTS 与 LTX 2.3 节点映射，不创建任务。"""

    settings = Settings.from_env()
    client = RunningHubClient(settings)
    qwen_result = await inspect_one_app(
        settings, client, settings.qwen, TTS_ROLE_ALIASES, ("script",)
    )
    if settings.ltx_mode == "workflow":
        ltx_result = inspect_ltx_workflow(settings)
    else:
        ltx_result = await inspect_one_app(
            settings,
            client,
            settings.ltx,
            LTX_NODE_ROLE_ALIASES,
            ("image", "audio", "prompt"),
        )
    return {
        "ok": qwen_result["ok"] and ltx_result["ok"],
        "base_url": settings.base_url,
        "qwen_tts": qwen_result,
        "ltx23": ltx_result,
        "state_file": settings.state_file,
        "inspection_created_task": False,
        "generation_will_consume_credits": True,
    }


@mcp.tool(
    meta={"openai/fileParams": ["image_file"]},
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": False,
        "openWorldHint": True,
    },
)
async def start_dialogue_video_from_script(
    image_file: OpenAIFile,
    dialogue_script: str,
    video_prompt: str,
    voice_a_prompt: str = "年轻中国女性，清亮自然，普通话，语速中等，情绪自然",
    voice_b_prompt: str = "年轻中国男性，温和略低沉，普通话，语速中等，情绪自然",
    sentence_pause: float = 0.0,
    punctuation_pause: float = 0.0,
    left_character: str = "",
    right_character: str = "",
    speaker_timeline: str = "",
    action: str = "说话者自然张嘴并有小幅表情和手势；未说话者自然倾听",
    camera: str = "固定中近景，轻微自然呼吸感，不切镜",
    negative_prompt: str = "字幕，文字，水印，角色换位，身份变化，两人同时开口，口型错位，面部畸形，闪烁",
    width: int = 0,
    height: int = 0,
    aspect_ratio: str = "",
    duration_seconds: int = 0,
    frame_count: int = 0,
    fps: int = 0,
    tts_seed: int = -1,
    ltx_seed: int = -1,
    auto_start_ltx: bool = True,
) -> dict[str, Any]:
    """上传双人图片并启动“台词→Qwen音频→LTX视频”流水线。会消耗 RH 币。"""

    inputs = pipeline_inputs(
        dialogue_script=dialogue_script,
        voice_a_prompt=voice_a_prompt,
        voice_b_prompt=voice_b_prompt,
        sentence_pause=sentence_pause,
        punctuation_pause=punctuation_pause,
        tts_seed=tts_seed,
        video_prompt=video_prompt,
        left_character=left_character,
        right_character=right_character,
        speaker_timeline=speaker_timeline,
        action=action,
        camera=camera,
        negative_prompt=negative_prompt,
        width=width,
        height=height,
        aspect_ratio=aspect_ratio,
        duration_seconds=duration_seconds,
        frame_count=frame_count,
        fps=fps,
        ltx_seed=ltx_seed,
        auto_start_ltx=auto_start_ltx,
    )
    settings = Settings.from_env()
    client = RunningHubClient(settings)
    image_filename = await upload_file_object(
        client, settings, image_file, expected_kind="image"
    )
    inputs["_uploaded_image_filename"] = image_filename
    return await submit_tts_pipeline(image_filename=image_filename, inputs=inputs)


finalize_openai_file_param_schema(start_dialogue_video_from_script, "image_file")


@mcp.tool(
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": False,
        "openWorldHint": True,
    }
)
async def start_dialogue_video_from_script_url(
    image_url: str,
    dialogue_script: str,
    video_prompt: str,
    voice_a_prompt: str = "年轻中国女性，清亮自然，普通话，语速中等，情绪自然",
    voice_b_prompt: str = "年轻中国男性，温和略低沉，普通话，语速中等，情绪自然",
    sentence_pause: float = 0.0,
    punctuation_pause: float = 0.0,
    left_character: str = "",
    right_character: str = "",
    speaker_timeline: str = "",
    action: str = "说话者自然张嘴并有小幅表情和手势；未说话者自然倾听",
    camera: str = "固定中近景，轻微自然呼吸感，不切镜",
    negative_prompt: str = "字幕，文字，水印，角色换位，身份变化，两人同时开口，口型错位，面部畸形，闪烁",
    width: int = 0,
    height: int = 0,
    aspect_ratio: str = "",
    duration_seconds: int = 0,
    frame_count: int = 0,
    fps: int = 0,
    tts_seed: int = -1,
    ltx_seed: int = -1,
    auto_start_ltx: bool = True,
) -> dict[str, Any]:
    """下载公网双人图片并启动完整对话视频流水线。会消耗 RH 币。"""

    inputs = pipeline_inputs(
        dialogue_script=dialogue_script,
        voice_a_prompt=voice_a_prompt,
        voice_b_prompt=voice_b_prompt,
        sentence_pause=sentence_pause,
        punctuation_pause=punctuation_pause,
        tts_seed=tts_seed,
        video_prompt=video_prompt,
        left_character=left_character,
        right_character=right_character,
        speaker_timeline=speaker_timeline,
        action=action,
        camera=camera,
        negative_prompt=negative_prompt,
        width=width,
        height=height,
        aspect_ratio=aspect_ratio,
        duration_seconds=duration_seconds,
        frame_count=frame_count,
        fps=fps,
        ltx_seed=ltx_seed,
        auto_start_ltx=auto_start_ltx,
    )
    settings = Settings.from_env()
    client = RunningHubClient(settings)
    image_filename = await upload_url(
        client, settings, image_url, expected_kind="image"
    )
    inputs["_uploaded_image_filename"] = image_filename
    return await submit_tts_pipeline(image_filename=image_filename, inputs=inputs)


@mcp.tool(
    meta={"openai/fileParams": ["image_file", "audio_file"]},
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": False,
        "openWorldHint": True,
    },
)
async def start_ltx23_from_ready_media(
    image_file: OpenAIFile,
    audio_file: OpenAIFile,
    video_prompt: str,
    left_character: str = "",
    right_character: str = "",
    speaker_timeline: str = "",
    action: str = "说话者自然张嘴并有小幅表情和手势；未说话者自然倾听",
    camera: str = "固定中近景，轻微自然呼吸感，不切镜",
    negative_prompt: str = "字幕，文字，水印，角色换位，身份变化，两人同时开口，口型错位，面部畸形，闪烁",
    width: int = 0,
    height: int = 0,
    aspect_ratio: str = "",
    duration_seconds: int = 0,
    frame_count: int = 0,
    fps: int = 0,
    ltx_seed: int = -1,
) -> dict[str, Any]:
    """跳过 Qwen 阶段，使用现成图片和完整对白音频启动 LTX。会消耗 RH 币。"""

    inputs = pipeline_inputs(
        dialogue_script="已提供现成音频",
        voice_a_prompt="",
        voice_b_prompt="",
        sentence_pause=0.0,
        punctuation_pause=0.0,
        tts_seed=-1,
        video_prompt=video_prompt,
        left_character=left_character,
        right_character=right_character,
        speaker_timeline=speaker_timeline,
        action=action,
        camera=camera,
        negative_prompt=negative_prompt,
        width=width,
        height=height,
        aspect_ratio=aspect_ratio,
        duration_seconds=duration_seconds,
        frame_count=frame_count,
        fps=fps,
        ltx_seed=ltx_seed,
        auto_start_ltx=True,
    )
    settings = Settings.from_env()
    client = RunningHubClient(settings)
    image_filename, audio_filename = await asyncio.gather(
        upload_file_object(client, settings, image_file, expected_kind="image"),
        upload_file_object(client, settings, audio_file, expected_kind="audio"),
    )
    inputs["_uploaded_image_filename"] = image_filename
    now = time.time()
    record = PipelineRecord(
        pipeline_id=secrets.token_urlsafe(18),
        status="TTS_READY",
        created_at=now,
        updated_at=now,
        image_filename=image_filename,
        audio_filename=audio_filename,
        inputs=inputs,
    )
    await get_store(settings).put(record)
    record = await submit_ltx_for_record(settings, client, record)
    result = pipeline_summary(record)
    result["generation_will_consume_credits"] = True
    return result


finalize_openai_file_param_schema(start_ltx23_from_ready_media, "image_file", "audio_file")


@mcp.tool(
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": True,
    }
)
async def continue_dialogue_pipeline_to_ltx(
    pipeline_id: str,
    speaker_timeline: str = "",
    video_prompt: str = "",
) -> dict[str, Any]:
    """将暂停在音频阶段的流水线继续提交给 LTX；可补充准确说话时间线。"""

    pipeline_id = ensure_text("pipeline_id", pipeline_id, max_length=200)
    if not pipeline_id:
        raise ValueError("pipeline_id 不能为空。")
    settings = Settings.from_env()
    store = get_store(settings)
    lock = _pipeline_locks.setdefault(pipeline_id, asyncio.Lock())
    async with lock:
        record = await store.get(pipeline_id)
        if record is None:
            return {
                "ok": False,
                "pipeline_id": pipeline_id,
                "status": "NOT_FOUND",
                "error": "找不到该流水线。",
            }
        if record.status != "WAITING_FOR_LTX":
            return {
                **pipeline_summary(record),
                "ok": False,
                "error": "只有 WAITING_FOR_LTX 状态可以调用此工具。",
            }
        if speaker_timeline.strip():
            record.inputs["speaker_timeline"] = ensure_text(
                "speaker_timeline", speaker_timeline, max_length=3000
            )
        if video_prompt.strip():
            record.inputs["video_prompt"] = ensure_text(
                "video_prompt", video_prompt, max_length=6000
            )
        record.inputs["auto_start_ltx"] = True
        record.status = "TTS_READY"
        await store.put(record)
        try:
            record = await submit_ltx_for_record(
                settings, RunningHubClient(settings), record
            )
        except Exception as exc:
            record.status = "FAILED"
            record.error = f"LTX 提交失败：{str(exc)[:800]}"
            record = await store.put(record)
        return pipeline_summary(record)


@mcp.tool(
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": True,
    }
)
async def query_dialogue_pipeline(
    pipeline_id: str, wait_seconds: int = 0
) -> dict[str, Any]:
    """推进并查询完整流水线；成功时返回 audio_url 和 video_urls。"""

    pipeline_id = ensure_text("pipeline_id", pipeline_id, max_length=200)
    if not pipeline_id:
        raise ValueError("pipeline_id 不能为空。")
    if not 0 <= wait_seconds <= 55:
        raise ValueError("wait_seconds 必须在 0–55 之间。")
    settings = Settings.from_env()
    store = get_store(settings)
    lock = _pipeline_locks.setdefault(pipeline_id, asyncio.Lock())
    deadline = time.monotonic() + wait_seconds

    async with lock:
        record = await store.get(pipeline_id)
        if record is None:
            return {
                "ok": False,
                "pipeline_id": pipeline_id,
                "status": "NOT_FOUND",
                "error": "找不到该流水线。若 Railway 刚重新部署，请检查是否配置了持久化 Volume。",
            }
        while True:
            record = await advance_pipeline(record)
            if record.status in {"SUCCESS", "FAILED", "WAITING_FOR_LTX"} or time.monotonic() >= deadline:
                return pipeline_summary(record)
            await asyncio.sleep(settings.poll_interval_seconds)


@mcp.tool(
    annotations={
        "readOnlyHint": True,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": False,
    }
)
async def list_recent_dialogue_pipelines(limit: int = 10) -> dict[str, Any]:
    """列出最近的流水线 ID 和状态，便于恢复查询；不会访问 RunningHub。"""

    if not 1 <= limit <= 50:
        raise ValueError("limit 必须在 1–50 之间。")
    settings = Settings.from_env()
    records = await get_store(settings).list_recent(limit)
    return {
        "ok": True,
        "pipelines": [pipeline_summary(record) for record in records],
    }


@mcp.custom_route("/health", methods=["GET"])
async def health(_: Request) -> JSONResponse:
    try:
        settings = Settings.from_env(require_credentials=False)
        config_error: str | None = None
    except ConfigurationError as exc:
        settings = None
        config_error = str(exc)
    return JSONResponse(
        {
            "status": "ok",
            "service": "runninghub-qwen-ltx-orchestrator",
            "mcp_path_configured": bool(os.getenv("MCP_PATH", "/mcp").strip()),
            "runninghub_api_key_configured": bool(settings and settings.api_key),
            "qwen_tts_webapp_id": settings.qwen.webapp_id if settings else "",
            "ltx23_webapp_id": settings.ltx.webapp_id if settings else "",
            "ltx23_mode": settings.ltx_mode if settings else "",
            "ltx23_workflow_id": settings.ltx_workflow_id if settings else "",
            "ltx23_workflow_api_file": (
                settings.ltx_workflow_api_file if settings else ""
            ),
            "state_file": settings.state_file if settings else "",
            "configuration_error": config_error,
        }
    )


@mcp.custom_route("/", methods=["GET"])
async def root(_: Request) -> JSONResponse:
    return JSONResponse(
        {
            "name": "RunningHub Qwen3-TTS + LTX 2.3 Orchestrator",
            "health": "/health",
            "mcp": "configured privately",
        }
    )


if __name__ == "__main__":
    mcp_path = os.getenv("MCP_PATH", "/mcp").strip() or "/mcp"
    if not mcp_path.startswith("/"):
        mcp_path = f"/{mcp_path}"
    mcp.run(
        transport="http",
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
        path=mcp_path,
    )
